name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v3

      # 2️⃣ Cache dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ios/Pods
            ios/Podfile.lock
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      # 3️⃣ Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # 4️⃣ Clean & get dependencies
      - run: flutter clean
      - run: flutter pub get

      # 5️⃣ Update CocoaPods
      - run: |
          cd ios
          pod repo update
          pod install --repo-update
        shell: bash

      # 6️⃣ Build iOS release (no code signing)
      - run: flutter build ios --release --no-codesign

      # 7️⃣ Create IPA
      - run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr FlutterIpaExport.ipa Payload
        shell: bash

      # 8️⃣ Upload IPA to GitHub Release
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: build-${{ github.run_number }}
          overwrite: true
          body: "Release build IPA"
